"module: components":
- changed-files:
  - any-glob-to-any-file: 'webforj-components/**'

"module: data":
- changed-files:
  - any-glob-to-any-file: 'webforj-data/**'

"module: dispatcher":
- changed-files:
  - any-glob-to-any-file: 'webforj-dispatcher/**'

"module: foundation":
- changed-files:
  - any-glob-to-any-file: 'webforj-foundation/**'

"module: plugins":
- changed-files:
  - any-glob-to-any-file: 'webforj-plugins/**'

"module: framework":
- changed-files:
  - any-glob-to-any-file: 'webforj/**'

"module: report-aggregate":
- changed-files:
  - any-glob-to-any-file: 'webforj-report-aggregate/**'

"module: spring":
- changed-files:
  - any-glob-to-any-file: 'webforj-spring/**'

"module: webswing":
- changed-files:
  - any-glob-to-any-file: 'webforj-webswing/**'

documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

POM:
- changed-files:
  - any-glob-to-any-file: '**/pom.xml'

BBj:
- changed-files:
  - any-glob-to-any-file: '**/*.bbj'
