name: "🐞 Bug report"
description: File a bug report
labels: ["Type: Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before submitting, please search for similar bug reports in the issues section to avoid duplicates.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of what the bug is.
      placeholder: "For instance: When I start my application, the browser only shows a blank screen. After refreshing the application is shown."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please tell us how to reproduce the bug.
      placeholder: Expected behavior and actual behavior.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Please provide a clear and concise description of what you expected to happen.
      placeholder: "for instance: The application should show the login screen after starting."
    validations:
      required: false
  - type: dropdown
    id: deployment
    attributes:
      label: Deployment
      description: Please let us know if you are deploying the app as WAR or running with BBj Services.
      options:
        - WAR (Default)
        - BBj Services
      default: 0
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please let us know your environment when reproducing the issue.
      placeholder: Operating System, webforJ version, Java version, Browser, etc.
    validations:
      required: true
