name: "🐞 Bug report"
description: Report a bug in webforJ
labels: ["Type: Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before submitting, please search for similar bug reports in the issues section to avoid duplicates.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of what the bug is.
      placeholder: "E.g., Clicking on a button in the sidebar does not load the associated page component."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please tell us how to reproduce the bug.
      placeholder: "E.g., Start the application, open the sidebar, click on the 'Settings' button, and observe that no page is loaded."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Please provide a clear and concise description of what you expected to happen.
      placeholder: "E.g., Clicking on the 'Settings' button should load the settings page component in the main view."
    validations:
      required: false
  - type: dropdown
    id: deployment
    attributes:
      label: Deployment
      description: Please let us know if you are deploying the app as WAR or running with BBj Services.
      options:
        - WAR (Default)
        - BBj Services
        - Spring Boot
      default: 0
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please let us know your environment when reproducing the issue.
      placeholder: "E.g., Windows 11, webforJ v24.20, Java 11, Firefox 118."
    validations:
      required: true
