name: "🚀 Feature Request"
description: Asking for a new feature or enhancement in webforJ
labels: ["Type: Feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!. Before submitting, please search for similar feature requests
        in the issues section to avoid duplicates.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe your motivation
      description: Please provide a clear and concise description of what the feature is.
      placeholder: "for instance: I would like to have a button to export the data to a CSV file from the table."
    validations:
      required: true
  - type: textarea
    id: expected-solution
    attributes:
      label: Describe the solution you'd like
      description: Please provide a clear and concise description of what you want to happen.
      placeholder: "for instance: I would like to have a context menu on the table to export the data to a CSV file."
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "for instance: I could use the browser's print functionality to save the data to a PDF file."
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Please provide any additional context or screenshots about the feature request here.
      placeholder: Additional context
