package com.webforj.router.views;

import com.webforj.component.element.ElementCompositeContainer;
import com.webforj.component.element.annotation.NodeName;
import com.webforj.router.annotation.Route;

@NodeName("view-auto-generated-name")
@Route()
class AutoGeneratedNameView extends ElementCompositeContainer {

}
