package com.webforj.mcp;

import io.modelcontextprotocol.server.McpServerFeatures.SyncResourceSpecification;
import io.modelcontextprotocol.spec.McpSchema.ReadResourceResult;
import io.modelcontextprotocol.spec.McpSchema.Resource;
import io.modelcontextprotocol.spec.McpSchema.TextResourceContents;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;

/**
 * Serves the page that boots the application inside a host.
 *
 * @author Hyyan Abo Fakher
 * @since 26.02
 */
public class McpAppResource {

  /**
   * The URI the resource of the root route is published under. Every other route publishes under
   * this URI extended by its route path.
   */
  static final String APP_RESOURCE_URI = "ui://webforj/app";

  /**
   * The media type that tells a host the resource is an interactive application.
   */
  static final String MIME_TYPE = "text/html;profile=mcp-app";

  // The served template is the minified build of app.html, regenerated by scripts/minify.js
  // whenever the source page changes.
  private static final String TEMPLATE = "/META-INF/mcp/app.min.html";
  private static final String ROOT_ROUTE = "/";
  private static final String SDK = "/META-INF/mcp/ext-apps-1.7.5.js";
  private static final String ORIGIN_PLACEHOLDER = "__WEBFORJ_ORIGIN__";
  private static final String SERVLET_PATH_PLACEHOLDER = "__SERVLET_PATH__";
  private static final String SDK_PLACEHOLDER = "__EXT_APPS_SDK__";
  private static final String EMBED_LOCATION_PLACEHOLDER = "__EMBED_LOCATION__";
  private static final String RESOURCE_NAME = "webforJ app";
  private static final String UI_KEY = "ui";
  private static final String CSP_KEY = "csp";
  private static final String WIDGET_CSP_KEY = "openai/widgetCSP";
  private static final String WIDGET_DOMAIN_KEY = "openai/widgetDomain";

  private final String servletPath;
  private final McpAppOrigin origin;
  private final String route;

  /**
   * Creates the resource of the root route for a deployment serving webforJ under the given prefix.
   *
   * @param servletPath the prefix the webforJ servlet answers on, empty for the root
   * @param origin the origin resolution of the deployment
   */
  public McpAppResource(String servletPath, McpAppOrigin origin) {
    this(servletPath, origin, ROOT_ROUTE);
  }

  /**
   * Creates the resource of one view route for a deployment serving webforJ under the given prefix.
   *
   * @param servletPath the prefix the webforJ servlet answers on, empty for the root
   * @param origin the origin resolution of the deployment
   * @param route the route the served page opens the application at
   */
  public McpAppResource(String servletPath, McpAppOrigin origin, String route) {
    this.servletPath = servletPath == null ? "" : servletPath;
    this.origin = origin;
    this.route = route == null || route.isBlank() ? ROOT_ROUTE : route;
  }

  /**
   * Returns the URI the resource of the given route is published under.
   *
   * @param route the route a view is registered under
   * @return the resource URI the tool of that route points at
   */
  public static String getUriOf(String route) {
    if (route == null || route.isBlank() || ROOT_ROUTE.equals(route)) {
      return APP_RESOURCE_URI;
    }

    return APP_RESOURCE_URI + route;
  }

  /**
   * Returns the specification a server publishes for the app resource.
   *
   * @return the resource specification
   */
  public SyncResourceSpecification toSpecification() {
    String uri = getUriOf(route);
    String name = ROOT_ROUTE.equals(route) ? RESOURCE_NAME : RESOURCE_NAME + " " + route;
    Resource resource = Resource.builder(uri, name).description("The webforJ application")
        .mimeType(MIME_TYPE).meta(resourceMeta()).build();

    // The policy rides the read contents as well, computed per read, because hosts apply the
    // sandbox policy from the contents they render and the origin may become known after start.
    return new SyncResourceSpecification(resource,
        (exchange,
            request) -> ReadResourceResult.builder(List.of(TextResourceContents
                .builder(request.uri(), render()).mimeType(MIME_TYPE).meta(resourceMeta()).build()))
                .build());
  }

  /**
   * Renders the page against the origin the host reaches the application on.
   *
   * @return the page
   * @throws IllegalStateException if no origin is known yet
   */
  public String render() {
    String resolved = origin.resolve();
    if (resolved == null) {
      throw new IllegalStateException("No origin is known for the webforJ MCP app. Set "
          + McpAppOptions.KEY_ORIGIN + " to the address the host reaches the application on.");
    }

    return Template.CONTENT.replace(ORIGIN_PLACEHOLDER, resolved)
        .replace(SERVLET_PATH_PLACEHOLDER, servletPath).replace(EMBED_LOCATION_PLACEHOLDER, route);
  }

  private Map<String, Object> resourceMeta() {
    String resolved = origin.resolve();
    if (resolved == null) {
      return Map.of();
    }

    // Both vocabularies are published, the specification's ui keys and the widget keys ChatGPT
    // reads, so every host finds the policy under the name it knows. No ui domain is published,
    // hosts that sandbox on a domain of their own derive it themselves and reject foreign values.
    return Map.of(UI_KEY, Map.of(CSP_KEY, contentSecurityPolicy(resolved)), WIDGET_CSP_KEY,
        widgetContentSecurityPolicy(resolved), WIDGET_DOMAIN_KEY, resolved);
  }

  private static Map<String, Object> contentSecurityPolicy(String origin) {
    String socketOrigin = origin.replaceFirst("^http", "ws");
    List<String> origins = List.of(origin);

    return Map.of("resourceDomains", origins, "frameDomains", origins, "connectDomains",
        List.of(origin, socketOrigin));
  }

  private static Map<String, Object> widgetContentSecurityPolicy(String origin) {
    String socketOrigin = origin.replaceFirst("^http", "ws");
    List<String> origins = List.of(origin);

    return Map.of("resource_domains", origins, "frame_domains", origins, "connect_domains",
        List.of(origin, socketOrigin));
  }

  private static String readResource(String path) {
    try (InputStream stream = McpAppResource.class.getResourceAsStream(path)) {
      if (stream == null) {
        throw new IllegalStateException("The app page is missing from the jar at " + path);
      }

      return new String(stream.readAllBytes(), StandardCharsets.UTF_8);
    } catch (IOException e) {
      throw new UncheckedIOException("Cannot read the app page at " + path, e);
    }
  }

  // Read on first use and kept, since the page and the SDK inside the jar never change. The
  // official MCP Apps SDK is inlined into the page, so the rendered document stays self
  // contained under the sandbox policy that forbids loading scripts from other origins.
  private static final class Template {
    private static final String CONTENT =
        readResource(TEMPLATE).replace(SDK_PLACEHOLDER, readResource(SDK));

    private Template() {
      // Constant holder
    }
  }
}
